---
- hosts: all
  become: true
  tasks:
# Session 1 , we will write a hardcoded distro code
# Below listed code will cover debian based systems
    - name: uninstall apache2 package "UBUNTU"
      apt:
        name: apache2
        state: absent
      when: ansible_distribution in ["Debian","Ubuntu"]
    - name: uninstall php support "UBUNTU"
      apt:
        name: libapache2-mod-php
        state: absent
      when: ansible_distribution in ["Debian","Ubuntu"]
# Below listed code will cover RPM based systems
    
    - name: uninstall apache2 package "CentOS"
      dnf:
        name: httpd
        state: absent
      when: ansible_distribution == "CentOS"
    - name: uninstall php support "CentOS"
      dnf:
        name: php
        state: absent
      when: ansible_distribution == "CentOS"
    