# Targeting specific nodes
---
- hosts: all
  become: true
  pre_tasks:
  - name: install updates "CentOS" 
    tags: always
    dnf:
      update_only : yes
      update_cache : yes
    when: ansible_distribution == "CentOS"
  - name: install updates "Ubuntu" 
    tags: always
    apt:
      upgrade : dist
      update_cache : yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install web server and php
    tags: apache, httpd, php, libapache2-mod-php, CentOS , UBUNTU
    package: 
      name:
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
- hosts: db_servers
  become: true
  tasks:
  - name: install database
    tags: mariadb, CentOS, UBUNTU
    package:
      name: "{{database_package}}"
      state: latest
- hosts: file_servers
  become: true
  tasks:
  - name: install file server
    tags: samba
    package:
      name: "{{fileserver_package}}"
      state: latest
