- name: install Unzip
  tags: workstation
  package:
    name: dnf

- name: install Unzip
  tags: workstation
  package:
    name: unzip
- name: install terraform
  tags: workstation
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_386.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
